// src/auth/domain/interfaces/tokens.ts
export const EMAIL_VERIFICATION_TOKEN_REPOSITORY = Symbol('EMAIL_VERIFICATION_TOKEN_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const EMAIL_SERVICE = Symbol('EMAIL_SERVICE');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const PASSWORD_RESET_TOKEN_REPOSITORY = Symbol('PASSWORD_RESET_TOKEN_REPOSITORY');
export const TOKEN_BLACKLIST = Symbol('TOKEN_BLACKLIST');